---
kind: pipeline
name: x64

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: configure
  image: webkitdev/msbuild:1809
  commands:
  - cmake -B build -S . -A x64 -DPORT=Win ..

- name: build
  image: webkitdev/msbuild:1809
  commands:
  - cmake --build build

when:
  branch:
    - webkit*
